# Site settings
title: Python 基础教程
email: heychilde@gmail.com
description: > 

baseurl: "/learn-python/" # the subpath of your site, e.g. /blog/
url: "http://git.dev.ctrip.com"

# Build settings
permalink: /:title.html
timezone: Asia/Shanghai
markdown: redcarpet
extensions: [fenced_code_blocks]
